// app/components/landing/WhySection.tsx
"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Lightbulb, X } from "lucide-react";

export default function WhySection() {
  type WhyItem = {
    id: number;
    title: string;
    desc: string;
  };

  const cards = [
    {
      id: 1,
      large: true,
      title: "Desain Elegan & Bersih",
      desc: "Dirancang dengan estetika modern yang menenangkan, memadukan warna lembut, tipografi rapi, serta hierarki visual yang konsisten untuk menciptakan pengalaman antarmuka yang indah, nyaman, dan mudah dipahami sejak pertama kali digunakan.",
      accent:
        "-top-6 -right-10 w-32 h-32 bg-[#AEC7DE]/40 blur-2xl rounded-full opacity-70 group-hover:opacity-90 transition-all absolute",
    },
    {
      id: 2,
      title: "Super Ringan",
      desc: "Dikembangkan dengan performa sebagai prioritas utama, memastikan aplikasi tetap cepat, responsif, dan stabil bahkan pada perangkat dengan spesifikasi rendah tanpa lag, tanpa delay, hanya pengalaman yang mulus.",
      accent:
        "top-2 right-3 w-16 h-16 bg-[#C9DAE8]/60 blur-xl rounded-full absolute",
    },
    {
      id: 3,
      title: "Terintegrasi Cerdas",
      desc: "Seluruh fitur saling terhubung secara otomatis sehingga alur kerja terasa natural dan efisien. Tidak perlu berpindah menu atau melakukan langkah manual yang rumit—semua terjadi secara pintar di belakang layar.",
      accent:
        "bottom-0 right-0 w-20 h-20 bg-[#AEC7DE]/50 blur-xl rounded-full absolute",
    },
    {
      id: 4,
      title: "Keamanan Prioritas",
      desc: "Setiap data pengguna dilindungi menggunakan standar enkripsi modern dan praktik keamanan terkini, memastikan privasi tetap terjaga dan semua aktivitas berlangsung dengan aman tanpa kompromi.",
      accent:
        "bottom-3 right-3 w-12 h-12 bg-[#AEC7DE]/60 blur-lg rounded-full absolute",
    },
    {
      id: 5,
      title: "Support Maksimal",
      desc: "Tim support responsif yang selalu siap membantu kapan pun dibutuhkan baik untuk panduan penggunaan, pemecahan masalah, maupun konsultasi fitur agar pengalaman kamu selalu optimal.",
      accent:
        "bottom-3 right-3 w-12 h-12 bg-[#AEC7DE]/60 blur-lg rounded-full absolute",
    },
    {
      id: 6,
      title: "Selalu Berkembang",
      desc: "Aplikasi ini terus berkembang mengikuti kebutuhan pengguna dengan update rutin yang tidak hanya menambah fitur, tetapi juga meningkatkan stabilitas, keamanan, dan pengalaman penggunaan.",
      accent:
        "-bottom-4 right-6 w-20 h-20 bg-[#B9D4EA]/60 blur-xl rounded-full absolute",
    },
  ];

  const [selected, setSelected] = useState<WhyItem | null>(null);

  return (
    <section
      id="why"
      className="relative w-full py-32 bg-linear-to-br from-[#EDF3FA] via-[#D6E3F1] to-[#AFC9E3] overflow-hidden"
    >
      {/* background shapes */}
      <div className="absolute -top-28 -left-28 w-[420px] h-[420px] bg-white/30 rounded-3xl blur-[90px]" />
      <div className="absolute -bottom-20 -right-16 w-[340px] h-[340px] bg-[#C8D8EB]/40 rounded-full blur-[110px]" />

      <div className="relative z-10 max-w-7xl mx-auto px-6 lg:px-12">
        <div className="text-center mb-20">
          <span className="px-5 py-2 w-fit mx-auto flex items-center gap-2 rounded-full bg-white/30 backdrop-blur-xl border border-white/40 text-[#2F3A4B] text-sm font-semibold shadow-sm">
            <Lightbulb className="w-4 h-4" />
            Mengapa Memilih Kami?
          </span>

          <h2 className="mt-6 text-4xl md:text-5xl font-extrabold text-[#2F3A4B]">
            Semua yang Kamu Butuhkan{" "}
            <span className="text-[#3B6A9E]">Dalam Satu Tempat</span>
          </h2>
        </div>

        {/* >>> ANIMATED GRID <<< */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {cards.map((card, i) => (
            <motion.div
              key={card.id}
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{
                duration: 0.4,
                delay: i * 0.12,
                ease: "easeOut",
              }}
              whileHover={{
                scale: 1.04,
                rotate: card.id % 2 === 0 ? 1 : -1,
                transition: { duration: 0.2 },
              }}
              onClick={() => setSelected(card)}
              className="cursor-pointer bg-white/50 backdrop-blur-xl rounded-2xl p-6 border border-white/40 shadow-md hover:shadow-xl transition-all"
            >
              <h3 className="text-xl font-semibold mb-3 text-[#2F3A4B]">
                {card.title}
              </h3>
              <p className="text-[#415167]/80 line-clamp-3">{card.desc}</p>
            </motion.div>
          ))}
        </div>

        {/* MODAL DETAIL */}
        <AnimatePresence>
          {selected && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 flex items-center justify-center bg-black/40 backdrop-blur-md z-50"
              onClick={() => setSelected(null)}
            >
              <motion.div
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.8, opacity: 0 }}
                className="bg-white/60 max-w-lg w-[90%] rounded-2xl p-8 shadow-xl border border-white/40 relative"
              >
                <button
                  className="absolute top-3 right-3 bg-white/60 p-2 rounded-full"
                  onClick={() => setSelected(null)}
                >
                  <X className="w-5 h-5" />
                </button>

                <h3 className="text-2xl font-bold mb-4">{selected.title}</h3>
                <p className="text-[#415167]/85">{selected.desc}</p>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
}

// src/components/landing/WhySection.vue
<template>
  <section
    id="why"
    ref="whySection"
    class="relative w-full py-32 bg-linear-to-br from-[#EDF3FA] via-[#D6E3F1] to-[#AFC9E3] overflow-hidden"
  >
    <!-- BACKGROUND SHAPES (SELALU TAMPIL, TANPA ANIMASI) -->
    <div
      class="absolute -top-28 -left-28 w-[420px] h-[420px] bg-white/30 rounded-3xl blur-[90px] rotate-12"
    ></div>

    <div
      class="absolute -bottom-20 -right-16 w-[340px] h-[340px] bg-[#C8D8EB]/40 rounded-full blur-[110px]"
    ></div>

    <!-- CONTENT YANG DI-ANIMASI -->
    <div
      :class="isVisible ? 'animate-show' : 'animate-hide'"
      class="relative z-10 max-w-7xl mx-auto px-6 lg:px-12"
    >
      <!-- HEADER -->
      <div class="text-center mb-20">
        <span
          class="px-5 py-2 w-fit mx-auto flex items-center gap-2 rounded-full bg-white/30 backdrop-blur-xl border border-white/40 text-[#2F3A4B] text-sm font-semibold shadow-sm"
        >
          <Lightbulb class="w-4 h-4 stroke-[#2F3A4B]" />
          Mengapa Memilih Kami?
        </span>

        <h2
          class="mt-6 text-4xl md:text-5xl font-extrabold text-[#2F3A4B] tracking-tight"
        >
          Semua yang Kamu Butuhkan
          <span class="text-[#3B6A9E]">Dalam Satu Tempat</span>
        </h2>

        <p
          class="text-[#415167]/75 max-w-2xl mx-auto mt-4 text-lg leading-relaxed"
        >
          Dirancang dengan kenyamanan & estetika modern. Satu platform untuk
          seluruh kebutuhan produktivitas kamu.
        </p>
      </div>

      <!-- DRAGGABLE BENTO GRID -->
      <draggable
        v-model="cards"
        item-key="id"
        animation="260"
        ghost-class="opacity-40"
        handle=".drag-handle"
        class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 auto-rows-[280px]"
      >
        <template #item="{ element }">
          <div
            :class="[
              'relative group p-8 rounded-3xl bg-white/30 backdrop-blur-2xl border border-white/40 shadow-[0_8px_30px_rgba(0,0,0,0.08)] hover:shadow-[0_15px_40px_rgba(0,0,0,0.12)] hover:scale-[1.015] transition-all duration-300 overflow-hidden',
              element.large ? 'col-span-1 lg:col-span-2' : '',
            ]"
          >
            <!-- DRAG HANDLE -->
            <div
              class="drag-handle absolute top-4 left-4 flex flex-col gap-[3px] opacity-40 group-hover:opacity-100 transition-opacity cursor-grab active:cursor-grabbing"
            >
              <span class="flex gap-[3px]">
                <span class="w-1.5 h-1.5 bg-[#2F3A4B]/30 rounded-sm"></span>
                <span class="w-1.5 h-1.5 bg-[#2F3A4B]/30 rounded-sm"></span>
              </span>
              <span class="flex gap-[3px]">
                <span class="w-1.5 h-1.5 bg-[#2F3A4B]/30 rounded-sm"></span>
                <span class="w-1.5 h-1.5 bg-[#2F3A4B]/30 rounded-sm"></span>
              </span>
            </div>

            <!-- Accent Shape -->
            <div
              v-if="element.accent"
              class="absolute"
              :class="element.accent"
            ></div>

            <h3
              class="text-xl md:text-2xl font-bold text-[#2F3A4B] mb-3 leading-tight"
            >
              {{ element.title }}
            </h3>

            <p class="text-[#415167]/80 leading-relaxed">
              {{ element.desc }}
            </p>
          </div>
        </template>
      </draggable>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";
import { Lightbulb } from "lucide-vue-next";
import draggable from "vuedraggable";

const cards = ref([
  {
    id: 1,
    large: true,
    title: "Desain Elegan & Bersih",
    desc: "Dirancang dengan estetika modern yang menenangkan, memadukan warna lembut, tipografi rapi, serta hierarki visual yang konsisten untuk menciptakan pengalaman antarmuka yang indah, nyaman, dan mudah dipahami sejak pertama kali digunakan.",
    accent:
      "-top-6 -right-10 w-32 h-32 bg-[#AEC7DE]/40 blur-2xl rounded-full opacity-70 group-hover:opacity-90 transition-all absolute",
  },
  {
    id: 2,
    title: "Super Ringan",
    desc: "Dikembangkan dengan performa sebagai prioritas utama, memastikan aplikasi tetap cepat, responsif, dan stabil bahkan pada perangkat dengan spesifikasi rendah tanpa lag, tanpa delay, hanya pengalaman yang mulus.",
    accent:
      "top-2 right-3 w-16 h-16 bg-[#C9DAE8]/60 blur-xl rounded-full absolute",
  },
  {
    id: 3,
    title: "Terintegrasi Cerdas",
    desc: "Seluruh fitur saling terhubung secara otomatis sehingga alur kerja terasa natural dan efisien. Tidak perlu berpindah menu atau melakukan langkah manual yang rumit—semua terjadi secara pintar di belakang layar.",
    accent:
      "bottom-0 right-0 w-20 h-20 bg-[#AEC7DE]/50 blur-xl rounded-full absolute",
  },
  {
    id: 4,
    title: "Keamanan Prioritas",
    desc: "Setiap data pengguna dilindungi menggunakan standar enkripsi modern dan praktik keamanan terkini, memastikan privasi tetap terjaga dan semua aktivitas berlangsung dengan aman tanpa kompromi.",
    accent:
      "bottom-3 right-3 w-12 h-12 bg-[#AEC7DE]/60 blur-lg rounded-full absolute",
  },
  {
    id: 5,
    title: "Support Maksimal",
    desc: "Tim support responsif yang selalu siap membantu kapan pun dibutuhkan baik untuk panduan penggunaan, pemecahan masalah, maupun konsultasi fitur agar pengalaman kamu selalu optimal.",
    accent:
      "bottom-3 right-3 w-12 h-12 bg-[#AEC7DE]/60 blur-lg rounded-full absolute",
  },
]);

const whySection = ref(null);
const isVisible = ref(false);

let observer = null;

onMounted(() => {
  observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        isVisible.value = entry.isIntersecting;
      });
    },
    { threshold: 0.25 }
  );

  if (whySection.value) observer.observe(whySection.value);
});

onBeforeUnmount(() => {
  if (observer && whySection.value) observer.unobserve(whySection.value);
});
</script>

<style scoped>
/* ANIMASI MASUK */
@keyframes fadeUpIn {
  0% {
    opacity: 0;
    transform: translateY(30px) scale(0.98);
  }
  100% {
    opacity: 1;
    transform: translateY(0) scale(1);
  }
}

/* ANIMASI KELUAR */
@keyframes fadeUpOut {
  0% {
    opacity: 1;
    transform: translateY(0) scale(1);
  }
  100% {
    opacity: 0;
    transform: translateY(30px) scale(0.98);
  }
}

/* STATE */
.animate-show {
  animation: fadeUpIn 0.8s ease-out forwards;
}

.animate-hide {
  animation: fadeUpOut 0.6s ease-out forwards;
}

/* Drag hint */
@keyframes subtleWiggle {
  0% {
    transform: translateX(0);
  }
  50% {
    transform: translateX(2px);
  }
  100% {
    transform: translateX(0);
  }
}

.drag-hint {
  animation: subtleWiggle 1.8s ease-in-out infinite;
}
.drag-hint:hover {
  animation: none;
}
</style>
